import os
import smtplib
from datetime import date
from email.mime.multipart import MIMEMultipart
from email.mime.text import MIMEText


def _build_html(words: list[dict], theme: str) -> str:
    date_str = date.today().strftime("%-d %b %Y")
    theme_title = theme.title()

    cards = ""
    for w in words:
        cards += f"""
        <div style="background:#ffffff;border-radius:8px;box-shadow:0 2px 6px rgba(0,0,0,0.08);
                    margin-bottom:16px;padding:20px 24px;">
            <div style="margin-bottom:10px;">
                <span style="font-size:20px;font-weight:bold;color:#1a1a1a;">{w['word']}</span>
                <span style="font-size:13px;color:#888;margin-left:10px;">{w['pos']}</span>
            </div>
            <div style="font-size:14px;color:#333;margin-bottom:6px;">
                🇬🇧 {w['translation']}
            </div>
            <div style="font-size:14px;color:#444;font-style:italic;">
                ✍️ {w['example_ru']}
            </div>
        </div>"""

    return f"""<!DOCTYPE html>
<html lang="ru">
<head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"></head>
<body style="margin:0;padding:0;background:#f5f5f5;font-family:Arial,Helvetica,sans-serif;">
  <div style="max-width:580px;margin:32px auto;padding:0 16px;">

    <div style="background:#2c3e50;border-radius:8px;padding:24px;margin-bottom:24px;color:#ffffff;">
      <div style="font-size:13px;opacity:0.7;margin-bottom:4px;">{date_str}</div>
      <div style="font-size:22px;font-weight:bold;">🇷🇺 Русский день</div>
      <div style="font-size:15px;opacity:0.85;margin-top:6px;">Theme: {theme_title}</div>
    </div>

    {cards}

    <div style="text-align:center;font-size:12px;color:#aaa;padding:16px 0;">
      Generated by your Russian vocab agent
    </div>
  </div>
</body>
</html>"""


def send_vocab_email(words: list[dict], theme: str) -> None:
    smtp_host = os.environ["SMTP_HOST"]
    smtp_port = int(os.environ["SMTP_PORT"])
    username = os.environ["SMTP_USERNAME"]
    password = os.environ["SMTP_PASSWORD"]
    sender = os.environ["SENDER_EMAIL"]
    recipient = os.environ["RECIPIENT_EMAIL"]

    date_str = date.today().strftime("%-d %b %Y")
    subject = f"🇷🇺 Русский день: {theme.title()} — {date_str}"

    msg = MIMEMultipart("alternative")
    msg["Subject"] = subject
    msg["From"] = sender
    msg["To"] = recipient
    msg.attach(MIMEText(_build_html(words, theme), "html", "utf-8"))

    with smtplib.SMTP(smtp_host, smtp_port) as server:
        server.ehlo()
        server.starttls()
        server.login(username, password)
        server.sendmail(sender, recipient, msg.as_string())
